// Sample data for suggestions
export const suggestionsData ={

 Tirupati:[
    //tirpathi
    "Tirupati", "Srikalahasti", "Gudur", "Puttur", "Venkatagiri", "Sullurpeta", "Naidupeta", "Bramhana Pattu", "Gundala", "Kandragaunta", "B.N.Kandriga", "Kallivettu", "Kammapalem", "Chandragiri", "Thondawada", "Ramireddipalle", "Abbiramapuram", "Daminedu", "Nelaturu", "Chinnagottigallu", "Devarakonda", "Yeguvauru", "Chittamur", "Eruru", "Gundluru", "Dakkili", "Kudithipalem", "Pathipadu", "Doravarisatram", "Inagaluru", "Koduru", "Mittapalem", "Anjuru", "Ellamanyam Kandriga", "Chintalapalem", "Kota", "Thimmasamudram", "Surutupalle", "Vepagunta", "Pudi", "Thonduru", "Kothapalle", "Thallambedu", "Damavaram", "Ozili", "Polireddipalem", "Chinnarajupalem", "Mangalampeta", "Pakala", "Kandriga", "Pellakur", "Vemireddy Kandriga", "Kothuru", "Thada", "Brahmanapattu", "Mallavaram", "Renigunta", "Mamanduru", "Thimminaidupalem", "Chitrakonda", "Airalamma Palle", "Kasuvaripalle", "Akkurthi", "Thondamanadu", "Irugulam", "Venkateswarapuram", "Kanuparti", "Vadamalapeta", "Venkatapuram", "Irapalle", "Vakadu", "Varadaiahpalem", "Mallemadugu", "Yerpedu", "Yerravaripalem", "Avilala", "Cherlopalle", "Tiruchanur"
    , "Tirupati",
    "Tiruchanur",
    "Avilala",
    "Renigunta",
    "Chandragiri",
    "Mangalam",
    "Thondawada",
    "Ramireddipalle",
    "Karakambadi",
    "Settipalli",
    "Govindarajapuram",
    "Bhavani Nagar",
    "Royal Nagar",
    "Rayalacheruvu",
    "Padmavathipuram",
    "Srinivasapuram",
    "Vidyanagar",
    "MR Palle",
    "SV University Area",
    "Kapila Theertham Area",
    "Alipiri",
    "Srikalahasti",
    "Puttur",
    "Gudur",
    "Naidupeta",
    "Venkatagiri",
    "Sullurpeta"],
    //anantapur
    Anantapur:[  "Anantapur", "Guntakal", "Tadipatri", "Rayadurgam", "Gooty", "Kalyandurg", "Dharmavaram", "Hindupur", "Kadiri", "Puttaparthi", "Pamidi", "Agali", "Amarapuram", "Amadagur", "Alamuru", "Itikalapalle", "Atmakur", "Beluguppa", "Bommanahal", "Brahmasamudram", "Bukkapatnam", "Bukkarayasamudram", "Chennekothapalli", "Chilamathur", "D.Hirehal", "Gandlapenta", "Garladinne", "Gorantla", "Gummagatta", "Kadiri Rural", "Kalyandurgam Rural", "Kambadur", "Kanekal", "Kothacheruvu", "Kudurpi", "Kundurpi", "Madakasira", "Nallamada", "Narpala", "Peddapappur", "Peddavadugur", "Putlur", "Rapthadu", "Roddam", "Setturu", "Singanamala", "Somandepalle", "Tadimarri", "Tanakallu", "Uravakonda", "Vajrakarur", "Vidapanakal", "Yadiki", "Yellanur",
"Puttaparthi",
"Penukonda",
"Dharmavaram",
"Kadiri",
"Hindupur",
"Gauribidanur",
"Bagepalli",
"Chelamacherla",
"Kothacheruvu",
"Obuladevaracheruvu",
"Talupula",
"Amadagur",
"Agali",
"Roddam",
"Somandepalle",
"Lepakshi",
"Chilamathur",
"Bukkapatnam",
"Brahmasamudram",
"Chennekothapalle",
"Gorantla",
"Gummagatta",
"Kambadur",
"Kothacheruvu",
"Kudurpi",
"Kundurpi",
"Madakasira",
"Nallamada",
"Peddapappur",
"Peddavadugur",
"Putlur",
"Rapthadu",
"Setturu",
"Tadimarri",
"Tanakallu",
"Vidapanakal",
"Yellanur"],
    //chittoor
    Chittoor:[ "Chittoor", "Madanapalle", "Nagari", "Palamaner", "Punganur", "Kuppam", "B.Kothakota", "Baireddipalle", "Bangarupalem", "Buchinaidu Kandriga", "Chandragiri", "Chinnagottigallu", "Chowdepalle", "Gangadhara Nellore", "Gangavaram", "Gudipala", "Gudupalle", "Gurramkonda", "Irala", "K.V.B.Puram", "Kalakada", "Kalikiri", "Kambhamvaripalle", "Karvetinagar", "Kurabalakota", "Mulakalacheruvu", "Nimmanapalle", "Nindra", "Palasamudram", "Pedda Thippasamudram", "Peddamandyam", "Peddapanjani", "Penumuru", "Pulicherla", "Puthalapattu", "Ramakuppam", "Ramasamudram", "Rompicherla", "Santhipuram", "Sodam", "Somala", "Srirangarajapuram", "Thamballapalle", "Thavanampalle", "Valmikipuram", "Vayalpadu", "Vepanapalle", "V Kota", "Vallur", "Vayalpad", "Yadamarri", "Yerravaripalem", "Yerpedu", "Yerramreddipalle", "Yerravaripalem", "Zangalapalle"],
     
    };
